plugins { id 'com.android.application' }

android {
    namespace 'com.chordlab.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chordlab.app'
        minSdk 23
        targetSdk 35
        versionCode 201
        versionName '0.2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug { minifyEnabled false }
    }
}
